In [49]:
file_name = "2022_전문대_학교별"

In [50]:
import pandas as pd

# 1. 엑셀 파일 읽기 (4번째·5번째 행을 헤더로 사용)
df = pd.read_excel(rf'C:\Users\Admin\Desktop\25공공교육데이터분석\OpenEdu2025\데이터\중도탈락 학생 현황_학교별평균값\전처리 전\{file_name}.xlsx', header=[3, 4])

In [51]:
# 2. 멀티인덱스 컬럼을 단일 레벨로 플래튼(flatten)
if isinstance(df.columns, pd.MultiIndex):
    new_cols = []
    for top, sub in df.columns:
        if pd.isna(sub):
            new_cols.append(str(top).strip())
        else:
            new_cols.append(f"{top.strip()}_{sub.strip()}")
    df.columns = new_cols
else:
    df.columns = [col.strip() for col in df.columns]

# 3. 컬럼 이름 간소화
df = df.rename(columns={
    '기준연도_Unnamed: 0_level_1': '기준연도',
    '학교종류_Unnamed: 1_level_1': '학교종류',
    '설립구분_Unnamed: 2_level_1': '설립구분',
    '지역_Unnamed: 3_level_1': '지역',
    '학교_Unnamed: 5_level_1': '학교명',
    '재적학생\n(A)_Unnamed: 6_level_1': '재적학생',
    '사유별 중도탈락 학생_자퇴': '자퇴학생',
    '재적학생\n(신입생)\n(A`)_Unnamed: 17_level_1': '신입생',
    '사유별 중도탈락 학생(신입생)_자퇴': '신입생_자퇴학생'
})

# 4. 필요한 열만 선택
selected_cols = [
    '기준연도', '학교종류', '설립구분', '지역', '학교명',
    '재적학생', '자퇴학생',
    '신입생', '신입생_자퇴학생'
]

df_selected = df[selected_cols].copy()


# 5. 자퇴학생비율, 신입생_자퇴학생비율 계산 추가
df_selected['자퇴학생비율'] = (df_selected['자퇴학생'] / df_selected['재적학생']) * 100
df_selected['신입생_자퇴학생비율'] = (df_selected['신입생_자퇴학생'] / df_selected['신입생']) * 100

# 6. 소수 둘째자리로 반올림 (선택사항)
df_selected['자퇴학생비율'] = df_selected['자퇴학생비율'].round(2)
df_selected['신입생_자퇴학생비율'] = df_selected['신입생_자퇴학생비율'].round(2)

# 원하는 컬럼 순서대로 다시 정렬
df_selected = df_selected[
    ['기준연도', '학교종류', '설립구분', '지역', '학교명',
     '재적학생', '자퇴학생', '자퇴학생비율',
     '신입생', '신입생_자퇴학생', '신입생_자퇴학생비율']
]

In [52]:
df_selected

,기준연도,학교종류,설립구분,지역,학교명,재적학생,자퇴학생,자퇴학생비율,신입생,신입생_자퇴학생,신입생_자퇴학생비율
0,2021,기능대학,사립,경기,ICT폴리텍대학,515,32,6.21,134,9,6.72
1,2021,전문대학,사립,경북,가톨릭상지대학교,2452,101,4.12,793,62,7.82
2,2021,전문대학,사립,충북,강동대학교,4526,157,3.47,1207,58,4.81
3,2021,전문대학,사립,강원,강릉영동대학교,4258,110,2.58,831,33,3.97
4,2021,전문대학,사립,강원,강원관광대학교,718,26,3.62,124,7,5.65
...,...,...,...,...,...,...,...,...,...,...,...
165,2021,전문대학,사립,강원,한림성심대학교,4267,162,3.80,1139,64,5.62
166,2021,전문대학,사립,서울,한양여자대학교,7661,382,4.99,3021,244,8.08
167,2021,전문대학,사립,전남,한영대학교,1794,68,3.79,667,42,6.30
168,2021,전문대학,사립,충남,혜전대학교,3373,91,2.70,951,53,5.57
169,2021,전문대학,사립,경북,호산대학교,2170,85,3.92,781,51,6.53

In [53]:
# 저장할 파일명/경로 지정
output_path = rf'C:\Users\Admin\Desktop\25공공교육데이터분석\OpenEdu2025\데이터\중도탈락 학생 현황_학교별평균값\전처리 후\{file_name}.xlsx'

# 1) 엑셀 파일로 저장
df_selected.to_excel(output_path, index=False)